name: PR lint

on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]

jobs:
  pr-lint:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - uses: seferov/pr-lint-action@v1.2.0
        with:
          title-regex: ^(\[(?!NO-TICKET|NO TICKET|NOTICKET)([A-Z0-9]|\s{1}){0,10}(-\d+)?\])+(\ )(?!.*[^\u0000-\u007F]+[\u00a9|\u00ae|[\u2000-\u3300]|\ud83c[\ud000-\udfff]|\ud83d[\ud000-\udfff]|\ud83e[\ud000-\udfff]+]).*$
